BEGIN;
SELECT plan(48);

SELECT has_schema('app', 'domain schema exists outside the exposed public API schema');
SELECT has_extension('postgis', 'PostGIS is enabled');
SELECT has_type('app', 'validation_state', 'validation state is explicit');
SELECT has_type('app', 'confidence_level', 'confidence remains qualitative until calibrated');
SELECT has_table('app', 'sources', 'sources exist');
SELECT has_table('app', 'source_approvals', 'field-scoped rights approvals exist');
SELECT has_table('app', 'source_references', 'source references exist');
SELECT has_table('app', 'raw_observations', 'rights-gated raw observations exist');
SELECT has_table('app', 'source_observations', 'normalized observations carry shared provenance');
SELECT has_table('app', 'locations', 'locations exist');
SELECT has_table('app', 'resorts', 'resorts exist');
SELECT has_table('app', 'resort_translations', 'resort translations exist separately');
SELECT has_table('app', 'resort_facts', 'provenanced resort facts exist');
SELECT has_table('app', 'map_features', 'spatial map features exist');
SELECT has_table('app', 'lifts', 'lifts exist separately');
SELECT has_table('app', 'pistes', 'pistes exist separately');
SELECT has_table('app', 'condition_observations', 'resort, lift and piste conditions are historical observations');
SELECT has_table('app', 'weather_stations', 'weather stations are separate locations');
SELECT has_table('app', 'weather_observations', 'observed weather is separate');
SELECT has_table('app', 'forecast_runs', 'forecast runs are separate from observations');
SELECT has_table('app', 'forecasts', 'forecast values are separate');
SELECT has_table('app', 'condition_score_versions', 'score algorithms are versioned');
SELECT has_table('app', 'condition_scores', 'condition score history exists');
SELECT has_table('app', 'condition_score_inputs', 'scores retain their inputs');
SELECT has_table('app', 'resort_rating_versions', 'resort rating versions exist');
SELECT has_table('app', 'resort_rating_categories', 'rating categories and weights exist');
SELECT has_table('app', 'resort_rating_values', 'resort rating values are separate');
SELECT has_table('app', 'resort_reviews', 'reviews remain a separate domain');
SELECT has_table('app', 'webcams', 'webcam references exist without image copies');
SELECT has_table('app', 'commercial_offers', 'commercial offers are separate');
SELECT hasnt_table('app', 'users', 'accounts are deferred');
SELECT hasnt_table('app', 'preferences', 'preferences are deferred');
SELECT hasnt_table('app', 'favorites', 'favorites are deferred');
SELECT hasnt_table('app', 'alerts', 'alerts are deferred');
SELECT hasnt_table('app', 'subscriptions', 'subscriptions are deferred');
SELECT hasnt_table('app', 'entitlements', 'entitlements are deferred');
SELECT has_view('app', 'v_condition_freshness', 'condition freshness is derived at read time');
SELECT has_view('app', 'v_weather_observation_freshness', 'weather freshness is derived at read time');
SELECT has_view('app', 'v_forecast_freshness', 'forecast freshness is derived at read time');
SELECT has_view('app', 'v_condition_score_freshness', 'score freshness is derived at read time');
SELECT has_index('app', 'map_features', 'map_features_geometry_gix', 'PostGIS geometry has a GiST index');
SELECT has_index('app', 'condition_scores', 'condition_scores_one_current_per_resort_uidx', 'only one current score per resort is allowed');
SELECT col_not_null('app', 'source_observations', 'fetched_at', 'normalized observation records retrieval time');
SELECT col_not_null('app', 'source_observations', 'source_reference_id', 'condition observations require provenance');
SELECT col_not_null('app', 'source_observations', 'validation_state', 'condition observations require validation state');
SELECT col_not_null('app', 'resorts', 'confidence_level', 'source-backed resort identity has confidence');
SELECT col_not_null('app', 'locations', 'validation_state', 'locations have validation state');
SELECT col_not_null('app', 'map_features', 'confidence_level', 'map features have confidence');

SELECT * FROM finish();
ROLLBACK;
